services:
  api:
    container_name: flashmemo_api
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_DB_PASS}
      DB_HOST: ${POSTGRES_DB_HOST}
      PIDFILE: /tmp/pids/server.pid
    volumes:
      - .:/usr/app
    tmpfs:
      - /tmp/pids/
    ports:
      - 3000:3000
    depends_on:
      - postgresql

  postgresql:
    container_name: flashmemo_postgresql
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data

  neo4j:
    container_name: flashmemo_graph
    image: neo4j:5.26
    ports:
      - 7474:7474
      - 7687:7687
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - neo4j-data:/data

volumes:
  pg-data:
  neo4j-data:
